use std::collections::HashMap;

use super::resolver::ResolvedPackage;
use super::version::{Version, VersionReq};

#[derive(Debug, Clone, PartialEq)]
pub struct Lockfile {
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct LockedPackage {
    pub name: String,
    pub version: Version,
}

impl Lockfile {
    pub fn from_resolved(resolved: Vec<ResolvedPackage>) -> Self {
        let mut packages: Vec<LockedPackage> = resolved
            .into_iter()
            .map(|p| LockedPackage {
                name: p.name,
                version: p.version,
            })
            .collect();
        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Lockfile { packages }
    }

    /// Parse an existing lyz.lock file
    pub fn parse(source: &str) -> Result<Self, String> {
        let mut packages = Vec::new();
        let mut current_name: Option<String> = None;
        let mut current_version: Option<Version> = None;

        for raw_line in source.lines() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if line == "[[package]]" {
                if let (Some(name), Some(version)) = (current_name.take(), current_version.take()) {
                    packages.push(LockedPackage { name, version });
                }
                continue;
            }

            if let Some((key, value)) = line.split_once('=') {
                let key = key.trim();
                let value = value.trim().trim_matches('"');
                match key {
                    "name" => current_name = Some(value.to_string()),
                    "version" => {
                        current_version = Some(
                            Version::parse(value)
                                .map_err(|e| format!("invalid version in lockfile: {}", e))?,
                        )
                    }
                    _ => {}
                }
            }
        }
        // Flush the last package (no trailing [[package]] marker follows it)
        if let (Some(name), Some(version)) = (current_name, current_version) {
            packages.push(LockedPackage { name, version });
        }

        packages.sort_by(|a, b| a.name.cmp(&b.name));
        Ok(Lockfile { packages })
    }

    pub fn to_lock_string(&self) -> String {
        let mut out = String::new();
        out.push_str("# This file is auto-generated by lyzard. Do not edit manually.\n\n");
        for pkg in &self.packages {
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = \"{}\"\n", pkg.name));
            out.push_str(&format!("version = \"{}\"\n\n", pkg.version));
        }
        out
    }

    /// Does this lockfile satisfy the given set of top-level requirements?
    /// (Used to decide whether `lyzard install` can skip re-resolution.)
    /// NOTE: this only checks TOP-LEVEL requirements directly, not the full
    /// transitive tree — a full check would re-run the resolver, which
    /// defeats the purpose of a fast-path lockfile check.
    pub fn satisfies(&self, requirements: &HashMap<String, VersionReq>) -> bool {
        for (name, req) in requirements {
            match self.packages.iter().find(|p| &p.name == name) {
                Some(locked) if req.matches(&locked.version) => continue,
                _ => return false,
            }
        }
        true
    }

    pub fn get(&self, name: &str) -> Option<&LockedPackage> {
        self.packages.iter().find(|p| p.name == name)
    }
}

#[cfg(test)]
mod lockfile_tests {
    use super::*;
    use crate::package::resolver::ResolvedPackage;

    fn resolved(name: &str, version: &str) -> ResolvedPackage {
        ResolvedPackage {
            name: name.to_string(),
            version: Version::parse(version).unwrap(),
        }
    }

    #[test]
    fn test_from_resolved_sorted_alphabetically() {
        let lock =
            Lockfile::from_resolved(vec![resolved("zebra", "1.0.0"), resolved("apple", "2.0.0")]);
        assert_eq!(lock.packages[0].name, "apple");
        assert_eq!(lock.packages[1].name, "zebra");
    }

    #[test]
    fn test_to_lock_string_format() {
        let lock = Lockfile::from_resolved(vec![resolved("foo", "1.2.3")]);
        let s = lock.to_lock_string();
        assert!(s.contains("[[package]]"));
        assert!(s.contains("name = \"foo\""));
        assert!(s.contains("version = \"1.2.3\""));
    }

    #[test]
    fn test_roundtrip_parse() {
        let lock = Lockfile::from_resolved(vec![resolved("a", "1.0.0"), resolved("b", "2.0.0")]);
        let s = lock.to_lock_string();
        let parsed = Lockfile::parse(&s).unwrap();
        assert_eq!(lock, parsed);
    }

    #[test]
    fn test_get_existing_package() {
        let lock = Lockfile::from_resolved(vec![resolved("http_client", "1.5.0")]);
        let pkg = lock.get("http_client").unwrap();
        assert_eq!(pkg.version, Version::new(1, 5, 0));
    }

    #[test]
    fn test_get_missing_package_none() {
        let lock = Lockfile::from_resolved(vec![]);
        assert!(lock.get("nothing").is_none());
    }

    #[test]
    fn test_satisfies_true_when_compatible() {
        let lock = Lockfile::from_resolved(vec![resolved("json", "1.5.0")]);
        let mut reqs = std::collections::HashMap::new();
        reqs.insert("json".to_string(), VersionReq::parse("^1.0.0").unwrap());
        assert!(lock.satisfies(&reqs));
    }

    #[test]
    fn test_satisfies_false_when_version_incompatible() {
        let lock = Lockfile::from_resolved(vec![resolved("json", "2.0.0")]);
        let mut reqs = std::collections::HashMap::new();
        reqs.insert("json".to_string(), VersionReq::parse("^1.0.0").unwrap());
        assert!(!lock.satisfies(&reqs));
    }

    #[test]
    fn test_satisfies_false_when_package_missing() {
        let lock = Lockfile::from_resolved(vec![]);
        let mut reqs = std::collections::HashMap::new();
        reqs.insert("missing_pkg".to_string(), VersionReq::parse("1.0.0").unwrap());
        assert!(!lock.satisfies(&reqs));
    }

    #[test]
    fn test_parse_ignores_header_comment() {
        let s = "# auto-generated\n\n[[package]]\nname = \"x\"\nversion = \"1.0.0\"\n";
        let lock = Lockfile::parse(s).unwrap();
        assert_eq!(lock.packages.len(), 1);
    }
}
